### ISSUE TITLE
Live streaming application architecture

### ISSUE THREAD

**Issue by letiesperon** [rootstrap/blog#16]
#### Motivation:

We worked on a live streaming application for Instagram influencers, that supported peak traffic from thousands fans that went crazy when an influencer started live streaming. This is how we did it and what we learnt from it.

---

#### :pushpin: Notes:

This is based on a start up that Germán and I worked at. The architecture is really interesting. 

I think it the post could be helpful to attract clients that want to scale and support this kind of traffic, and might attract talent that want to work on cool and challenging projects like this one was. 

---

#### :mag: Keywords:

ruby on rails, go, architecture, traffic, performance, scaling, live streaming, secretly

---

**Comment by glm4** [comment]
Closed in #159
