### ISSUE TITLE
Custom sidebar filters for Active Admin

### ISSUE THREAD

**Issue by letiesperon** [rootstrap/blog#18]
#### Motivation:

Sometimes we want to add filters in an ActiveAdmin model page that use scopes that are not just a simple 'where' clause applied to only one column of the table. 

---

#### :pushpin: Notes:

There is not much information about this around so I thought this small post might be useful.

---

#### :mag: Keywords:

ruby on rails, activeadmin, filters, sidebar, ransack, scope

---

**Comment by glm4** [comment]
Done in #19
