### ISSUE TITLE
Payment platforms options

### ISSUE THREAD

**Issue by gonzaM** [rootstrap/blog#22]
#### Motivation:

There are a lot of apps that need to manage payments, and it would be great to list some options. Especially, because depending on what you are implementing, the options may change.
Also, it would be good to mention what a marketplace is and what are the options.

---

#### :pushpin: Notes:

- List payment options.
- Talk about marketplace platforms.
- Differentiate between virtual and physical goods.

The idea is to create more posts related payments, but with more detail. One for Stripe, another one for Braintree, Dwolla, etc.

---

#### :mag: Keywords:

payments, stripe, braintree, paypal, dwolla

---

**Comment by glm4** [comment]
@gonzaM we can close this issue right?

**Comment by gonzaM** [comment]
Oh yes, I forgot it
