### ISSUE TITLE
Article: Kanban Vs Scrum

### ISSUE THREAD

**Issue by MC-Victoria** [rootstrap/blog#27]
#### Motivation:

Provide a catchy description of the subject you are proposing to write about.

---

#### :pushpin: Notes:

Include thoughts, ideas, questions, concerns or anything you think might be useful to create an interesting blog post.
Remember to assign the issue to yourself if you are planning to be the one to tackle it.

---

#### :mag: Keywords:

List the keywords that can be used to search for this post.
Remember to also tag the issue with the corresponding categories.

---

**Comment by glm4** [comment]
@missx @MC-Victoria Please update the description with the proper information.

**Comment by missx** [comment]
I'm going to close this one, as I don't think @MC-Victoria will write about this. We can reopen in the future if it will be done.
