### ISSUE TITLE
Animations in React Native

### ISSUE THREAD

**Issue by fernandatoledo** [rootstrap/blog#93]
#### Motivation:

Animations enhance user experience and can make a product differentiate itself from the competitors, but adding animations for the first time can be a true challenge, the idea is to share our previous experiences and make a useful guide.

---

#### :pushpin: Notes:

Official documentation: https://reactnative.dev/docs/0.51/animations
Useful post: https://medium.com/react-native-training/react-native-animations-using-the-animated-api-ebe8e0669fae
---

#### :mag: Keywords:

ReactNative, Animations

---

**Comment by glm4** [comment]
closed in #126
